version: '3'
services:
  mongo:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
  mongo-seeder:
    image: docker.pkg.github.com/votUCA/seeder/seeder:0.0.3
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=mongo
    links:
      - mongo
    depends_on:
      - mongo
