version: "3"
services:
  mongo:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
  mongo-seeder:
    build:
      context: ..
      dockerfile: .devcontainer/seeder.dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=mongo
    links:
      - mongo
    depends_on:
      - mongo
  app:
    build:
      context: ..
      dockerfile: .devcontainer/app.dockerfile
    volumes:
      - ..:/workspace
      - /workspace/node_modules
      - ~/.ssh:/root/.ssh-localhost:ro
    env_file:
      - ../.env
    command: /bin/sh -c "cd workspace/ && yarn start:dev"
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo
    depends_on:
      - mongo
